# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_library:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global deps
        run: |
          npm install -g strapi
          npm install -g @angular/cli
      - name: Install project dependencies
        run: npm install
      - name: Lint library project
        run: ng lint --project strapi-auth
      - name: Build library
        run: npm run build_lib
  build_showcase:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global deps
        run: |
          npm install -g strapi
          npm install -g @angular/cli
      - name: Install project dependencies
        run: npm install
      - name: Lint library project
        run: ng lint --project strapi-auth-showcase
      - name: Build showcase
        run: cd projects/strapi-auth-showcase && ng build
      - name: Build strapi
        run: cd projects/strapi-auth-showcase/strapi_backend && strapi build
